name: Continuous Deployment to Firebase

on: 
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install Dependencies
        run: npm ci
      - name: Create the Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
