name: Continuous Deployment to Firebase

on:
  release:
    types: [publish]
    
jobs:
  deploy:
      name: Deploy to Firebase
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Setup Node.js Environment
          uses: actions/setup-node@master
          with:
            node-version: '10.x'
        - name: Install Dependencies
          run: npm ci
        - name: Run Firebase Deploy
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting,functions
          env: 
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
