name: Continuous Deploy to Firebase
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Install Dependencies for Hosting and Functions
        run: npm ci && cd functions && npm ci && cd ..
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting,functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  notify:
    needs: [deploy]
    runs-on: ubuntu-latest
    name: Post Deploy Status to Slack
    steps:
      - name: Slack Workflow Notifications
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: 'transcrypt.app Workflow Bot'
          icon_url: 'https://transcrypt.app/assets/icons/android-chrome-192x192.png'
