name: Continuous Deploy to Firebase

on: 
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Install Firebase CLI
        run: npm install -d firebase-tools
      - name: Install Release Dependencies
        run: npm run install:ci
      - name: Build Release for Deployment
        run: npm run build:ci
      - name: Add Environment Variables to the Back-End
        run: npx firebase functions:config:set stripe.secret=${{ secrets.STRIPE_BACKEND }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase
        run: npx firebase deploy --only hosting,functions --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}