name: Continuous Integration Checks
on:
  pull_request:
    branches: [master]
jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: '10.x'
      - name: Install Dependencies
        run: npm run install:ci
      - name: Run Build
        run: npm run build:ci
       
