name: Release
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: '10.x'
      - run: npm ci
      - run: npm test
      - run: npm run build
    
       
