name: Continuous Integration Checks
on:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with: 
          node-version: '10.x'
      - name: Install Dependencies
        run: npm run install:ci
      - name: Run Build
        run: npm run build:ci
  notify:
    needs: [build]
    runs-on: ubuntu-latest
    name: Post CI Check Status to Slack
    steps:
      - name: Slack Workflow Notifications
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: 'transcrypt.app Workflow Bot'
          icon_url: 'https://transcrypt.app/assets/icons/android-chrome-192x192.png'
       
