name: Continuous Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Install the Semantic Release Dependencies
        run: npm install -D semantic-release @semantic-release/git @semantic-release/npm @semantic-release/exec last-release-git
      - name: Create the Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  notify:
    needs: [release]
    runs-on: ubuntu-latest
    name: Post Deploy Status to Slack
    steps:
      - name: Slack Workflow Notifications
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          name: 'transcrypt.app Workflow Bot'
          icon_url: 'https://transcrypt.app/assets/icons/android-chrome-192x192.png'
