name: Continuous Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@master
      - name: Setup Node.js Environment
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Install the Semantic Release Dependencies
        run: npm install -D semantic-release @semantic-release/git @semantic-release/npm last-release-git
      - name: Create the Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
